services:
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - openwebui_data:/app/backend/data 
    extra_hosts:
      - "host.docker.internal:host-gateway"

  comfyui-boot:
    stdin_open: true
    tty: true
    container_name: comfyui-cu124
    ports:
      - "8288:8188"
    volumes:
      - comfyui_data:/root
    image: yanwk/comfyui-boot:cu124-slim
    deploy:
      resources:
        reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities:
                  - gpu
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
volumes:
  ollama_data:
  openwebui_data:
  comfyui_data: 
